/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VirtualDeviceWrapper */

#ifndef _Included_VirtualDeviceWrapper
#define _Included_VirtualDeviceWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef VirtualDeviceWrapper_MIN_PRIORITY
#define VirtualDeviceWrapper_MIN_PRIORITY 1L
#undef VirtualDeviceWrapper_NORM_PRIORITY
#define VirtualDeviceWrapper_NORM_PRIORITY 5L
#undef VirtualDeviceWrapper_MAX_PRIORITY
#define VirtualDeviceWrapper_MAX_PRIORITY 10L
/*
 * Class:     VirtualDeviceWrapper
 * Method:    main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_VirtualDeviceWrapper_main
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
